use crate::chord::Chord;
use once_cell::sync::Lazy;
use std::collections::HashMap;

// chord formulas follow www.pianochord.org, whose per-root index pages
// (e.g. pianochord.org/c.html) list every supported chord type
#[rustfmt::skip]
pub static ALL_CHORDS: &'static [Chord] = &[
    // NOTE: major is omitted such that A ≡ A major by default
    // ─┬C┬┬D┬─┬─┬F┬┬G┬┬A┬─
    //  └┬┘└┬┘ │ └┬┘└┬┘└┬┘ 
    // c─┴d─┴e─┴f─┴g─┴a─┴b─
    // use the `-` separator to add another section to the keyboard
    Chord::new(&["C"], "ceg", &["C"]),
    Chord::new(&["C5"], "cg", &["C 5ᵗʰ"]),
    Chord::new(&["C7"], "cegA", &["C 7ᵗʰ"]),
    Chord::new(&["Cmaj7"], "cegb", &["C raised 7ᵗʰ"]),
    Chord::new(&["C6"], "cega", &["C 6ᵗʰ"]),
    Chord::new(&["C6/9"], "cega-d", &["C 6ᵗʰ added 9ᵗʰ"]),
    Chord::new(&["Cadd2"], "cdeg", &["C added 2ⁿᵈ"]),
    Chord::new(&["Cadd9"], "ceg-d", &["C added 9ᵗʰ"]),
    Chord::new(&["Csus2"], "cdg", &["C suspended 2ⁿᵈ"]),
    Chord::new(&["Csus", "Csus4"], "cfg", &["C suspended", "C suspended 4ᵗʰ"]),
    Chord::new(&["C7sus4"], "cfgA", &["C 7ᵗʰ suspended 4ᵗʰ"]),
    Chord::new(&["C9"], "cegA-d", &["C 9ᵗʰ"]),
    Chord::new(&["Cmaj9"], "cegb-d", &["C raised 9ᵗʰ"]),
    Chord::new(&["C11"], "cegA-df", &["C 11ᵗʰ"]),
    Chord::new(&["C13"], "cegA-dfa", &["C 13ᵗʰ"]),
    Chord::new(&["Cmaj13"], "cegb-da", &["C raised 13ᵗʰ"]),
    Chord::new(&["Cm"], "cDg", &["C minor"]),
    Chord::new(&["Cm6"], "cDga", &["C minor 6ᵗʰ"]),
    Chord::new(&["Cm7"], "cDgA", &["C minor 7ᵗʰ"]),
    Chord::new(&["Cmmaj7", "CmM7"], "cDgb", &["C minor raised 7ᵗʰ", "C minor major 7ᵗʰ"]),
    Chord::new(&["Cm9"], "cDgA-d", &["C minor 9ᵗʰ"]),
    Chord::new(&["Cm11"], "cDgA-df", &["C minor 11ᵗʰ"]),
    Chord::new(&["Cm7b5"], "cDFA", &["C half-diminished"]),
    Chord::new(&["Cdim"], "cDF", &["C diminished"]),
    Chord::new(&["Cdim7"], "cDFa", &["C diminished 7ᵗʰ"]),
    Chord::new(&["C7b5"], "ceFA", &["C 7ᵗʰ flat 5ᵗʰ"]),
    Chord::new(&["C+"], "ceG", &["C augmented"]),
    Chord::new(&["C7#5", "C+7"], "ceGA", &["C 7ᵗʰ sharp 5ᵗʰ", "C augmented 7ᵗʰ"]),
    Chord::new(&["C#", "Db"], "CfG", &["C♯", "D♭"]),
    Chord::new(&["C#5", "Db5"], "CG", &["C♯ 5ᵗʰ", "D♭ 5ᵗʰ"]),
    Chord::new(&["C#7", "Db7"], "CfGb", &["C♯ 7ᵗʰ", "D♭ 7ᵗʰ"]),
    Chord::new(&["C#maj7", "Dbmaj7"], "CfG-c", &["C♯ raised 7ᵗʰ", "D♭ raised 7ᵗʰ"]),
    Chord::new(&["C#6", "Db6"], "CfGA", &["C♯ 6ᵗʰ", "D♭ 6ᵗʰ"]),
    Chord::new(&["C#6/9", "Db6/9"], "CfGA-D", &["C♯ 6ᵗʰ added 9ᵗʰ", "D♭ 6ᵗʰ added 9ᵗʰ"]),
    Chord::new(&["C#add2", "Dbadd2"], "CDfG", &["C♯ added 2ⁿᵈ", "D♭ added 2ⁿᵈ"]),
    Chord::new(&["C#add9", "Dbadd9"], "CfG-D", &["C♯ added 9ᵗʰ", "D♭ added 9ᵗʰ"]),
    Chord::new(&["C#sus2", "Dbsus2"], "CDG", &["C♯ suspended 2ⁿᵈ", "D♭ suspended 2ⁿᵈ"]),
    Chord::new(&["C#sus", "C#sus4", "Dbsus", "Dbsus4"], "CFG", &["C♯ suspended", "C♯ suspended 4ᵗʰ", "D♭ suspended", "D♭ suspended 4ᵗʰ"]),
    Chord::new(&["C#7sus4", "Db7sus4"], "CFGb", &["C♯ 7ᵗʰ suspended 4ᵗʰ", "D♭ 7ᵗʰ suspended 4ᵗʰ"]),
    Chord::new(&["C#9", "Db9"], "CfGb-D", &["C♯ 9ᵗʰ", "D♭ 9ᵗʰ"]),
    Chord::new(&["C#maj9", "Dbmaj9"], "CfG-cD", &["C♯ raised 9ᵗʰ", "D♭ raised 9ᵗʰ"]),
    Chord::new(&["C#11", "Db11"], "CfGb-DF", &["C♯ 11ᵗʰ", "D♭ 11ᵗʰ"]),
    Chord::new(&["C#13", "Db13"], "CfGb-DFA", &["C♯ 13ᵗʰ", "D♭ 13ᵗʰ"]),
    Chord::new(&["C#maj13", "Dbmaj13"], "CfG-cDA", &["C♯ raised 13ᵗʰ", "D♭ raised 13ᵗʰ"]),
    Chord::new(&["C#m", "Dbm"], "CeG", &["C♯ minor", "D♭ minor"]),
    Chord::new(&["C#m6", "Dbm6"], "CeGA", &["C♯ minor 6ᵗʰ", "D♭ minor 6ᵗʰ"]),
    Chord::new(&["C#m7", "Dbm7"], "CeGb", &["C♯ minor 7ᵗʰ", "D♭ minor 7ᵗʰ"]),
    Chord::new(&["C#mmaj7", "C#mM7", "Dbmmaj7", "DbmM7"], "CeG-c", &["C♯ minor raised 7ᵗʰ", "C♯ minor major 7ᵗʰ", "D♭ minor raised 7ᵗʰ", "D♭ minor major 7ᵗʰ"]),
    Chord::new(&["C#m9", "Dbm9"], "CeGb-D", &["C♯ minor 9ᵗʰ", "D♭ minor 9ᵗʰ"]),
    Chord::new(&["C#m11", "Dbm11"], "CeGb-DF", &["C♯ minor 11ᵗʰ", "D♭ minor 11ᵗʰ"]),
    Chord::new(&["C#m7b5", "Dbm7b5"], "Cegb", &["C♯ half-diminished", "D♭ half-diminished"]),
    Chord::new(&["C#dim", "Dbdim"], "Ceg", &["C♯ diminished", "D♭ diminished"]),
    Chord::new(&["C#dim7", "Dbdim7"], "CegA", &["C♯ diminished 7ᵗʰ", "D♭ diminished 7ᵗʰ"]),
    Chord::new(&["C#7b5", "Db7b5"], "Cfgb", &["C♯ 7ᵗʰ flat 5ᵗʰ", "D♭ 7ᵗʰ flat 5ᵗʰ"]),
    Chord::new(&["C#+", "Db+"], "Cfa", &["C♯ augmented", "D♭ augmented"]),
    Chord::new(&["C#7#5", "C#+7", "Db7#5", "Db+7"], "Cfab", &["C♯ 7ᵗʰ sharp 5ᵗʰ", "C♯ augmented 7ᵗʰ", "D♭ 7ᵗʰ sharp 5ᵗʰ", "D♭ augmented 7ᵗʰ"]),
    Chord::new(&["D"], "dFa", &["D"]),
    Chord::new(&["D5"], "da", &["D 5ᵗʰ"]),
    Chord::new(&["D7"], "dFa-c", &["D 7ᵗʰ"]),
    Chord::new(&["Dmaj7"], "dFa-C", &["D raised 7ᵗʰ"]),
    Chord::new(&["D6"], "dFab", &["D 6ᵗʰ"]),
    Chord::new(&["D6/9"], "dFab-e", &["D 6ᵗʰ added 9ᵗʰ"]),
    Chord::new(&["Dadd2"], "deFa", &["D added 2ⁿᵈ"]),
    Chord::new(&["Dadd9"], "dFa-e", &["D added 9ᵗʰ"]),
    Chord::new(&["Dsus2"], "dea", &["D suspended 2ⁿᵈ"]),
    Chord::new(&["Dsus", "Dsus4"], "dga", &["D suspended", "D suspended 4ᵗʰ"]),
    Chord::new(&["D7sus4"], "dga-c", &["D 7ᵗʰ suspended 4ᵗʰ"]),
    Chord::new(&["D9"], "dFa-ce", &["D 9ᵗʰ"]),
    Chord::new(&["Dmaj9"], "dFa-Ce", &["D raised 9ᵗʰ"]),
    Chord::new(&["D11"], "dFa-ceg", &["D 11ᵗʰ"]),
    Chord::new(&["D13"], "dFa-cegb", &["D 13ᵗʰ"]),
    Chord::new(&["Dmaj13"], "dFa-Ceb", &["D raised 13ᵗʰ"]),
    Chord::new(&["Dm"], "dfa", &["D minor"]),
    Chord::new(&["Dm6"], "dfab", &["D minor 6ᵗʰ"]),
    Chord::new(&["Dm7"], "dfa-c", &["D minor 7ᵗʰ"]),
    Chord::new(&["Dmmaj7", "DmM7"], "dfa-C", &["D minor raised 7ᵗʰ", "D minor major 7ᵗʰ"]),
    Chord::new(&["Dm9"], "dfa-ce", &["D minor 9ᵗʰ"]),
    Chord::new(&["Dm11"], "dfa-ceg", &["D minor 11ᵗʰ"]),
    Chord::new(&["Dm7b5"], "dfG-c", &["D half-diminished"]),
    Chord::new(&["Ddim"], "dfG", &["D diminished"]),
    Chord::new(&["Ddim7"], "dfGb", &["D diminished 7ᵗʰ"]),
    Chord::new(&["D7b5"], "dFG-c", &["D 7ᵗʰ flat 5ᵗʰ"]),
    Chord::new(&["D+"], "dFA", &["D augmented"]),
    Chord::new(&["D7#5", "D+7"], "dFA-c", &["D 7ᵗʰ sharp 5ᵗʰ", "D augmented 7ᵗʰ"]),
    Chord::new(&["D#", "Eb"], "DgA", &["D♯", "E♭"]),
    Chord::new(&["D#5", "Eb5"], "DA", &["D♯ 5ᵗʰ", "E♭ 5ᵗʰ"]),
    Chord::new(&["D#7", "Eb7"], "DgA-C", &["D♯ 7ᵗʰ", "E♭ 7ᵗʰ"]),
    Chord::new(&["D#maj7", "Ebmaj7"], "DgA-d", &["D♯ raised 7ᵗʰ", "E♭ raised 7ᵗʰ"]),
    Chord::new(&["D#6", "Eb6"], "DgA-c", &["D♯ 6ᵗʰ", "E♭ 6ᵗʰ"]),
    Chord::new(&["D#6/9", "Eb6/9"], "DgA-cf", &["D♯ 6ᵗʰ added 9ᵗʰ", "E♭ 6ᵗʰ added 9ᵗʰ"]),
    Chord::new(&["D#add2", "Ebadd2"], "DfgA", &["D♯ added 2ⁿᵈ", "E♭ added 2ⁿᵈ"]),
    Chord::new(&["D#add9", "Ebadd9"], "DgA-f", &["D♯ added 9ᵗʰ", "E♭ added 9ᵗʰ"]),
    Chord::new(&["D#sus2", "Ebsus2"], "DfA", &["D♯ suspended 2ⁿᵈ", "E♭ suspended 2ⁿᵈ"]),
    Chord::new(&["D#sus", "D#sus4", "Ebsus", "Ebsus4"], "DGA", &["D♯ suspended", "D♯ suspended 4ᵗʰ", "E♭ suspended", "E♭ suspended 4ᵗʰ"]),
    Chord::new(&["D#7sus4", "Eb7sus4"], "DGA-C", &["D♯ 7ᵗʰ suspended 4ᵗʰ", "E♭ 7ᵗʰ suspended 4ᵗʰ"]),
    Chord::new(&["D#9", "Eb9"], "DgA-Cf", &["D♯ 9ᵗʰ", "E♭ 9ᵗʰ"]),
    Chord::new(&["D#maj9", "Ebmaj9"], "DgA-df", &["D♯ raised 9ᵗʰ", "E♭ raised 9ᵗʰ"]),
    Chord::new(&["D#11", "Eb11"], "DgA-CfG", &["D♯ 11ᵗʰ", "E♭ 11ᵗʰ"]),
    Chord::new(&["D#13", "Eb13"], "DgA-CfG-c", &["D♯ 13ᵗʰ", "E♭ 13ᵗʰ"]),
    Chord::new(&["D#maj13", "Ebmaj13"], "DgA-df-c", &["D♯ raised 13ᵗʰ", "E♭ raised 13ᵗʰ"]),
    Chord::new(&["D#m", "Ebm"], "DFA", &["D♯ minor", "E♭ minor"]),
    Chord::new(&["D#m6", "Ebm6"], "DFA-c", &["D♯ minor 6ᵗʰ", "E♭ minor 6ᵗʰ"]),
    Chord::new(&["D#m7", "Ebm7"], "DFA-C", &["D♯ minor 7ᵗʰ", "E♭ minor 7ᵗʰ"]),
    Chord::new(&["D#mmaj7", "D#mM7", "Ebmmaj7", "EbmM7"], "DFA-d", &["D♯ minor raised 7ᵗʰ", "D♯ minor major 7ᵗʰ", "E♭ minor raised 7ᵗʰ", "E♭ minor major 7ᵗʰ"]),
    Chord::new(&["D#m9", "Ebm9"], "DFA-Cf", &["D♯ minor 9ᵗʰ", "E♭ minor 9ᵗʰ"]),
    Chord::new(&["D#m11", "Ebm11"], "DFA-CfG", &["D♯ minor 11ᵗʰ", "E♭ minor 11ᵗʰ"]),
    Chord::new(&["D#m7b5", "Ebm7b5"], "DFa-C", &["D♯ half-diminished", "E♭ half-diminished"]),
    Chord::new(&["D#dim", "Ebdim"], "DFa", &["D♯ diminished", "E♭ diminished"]),
    Chord::new(&["D#dim7", "Ebdim7"], "DFa-c", &["D♯ diminished 7ᵗʰ", "E♭ diminished 7ᵗʰ"]),
    Chord::new(&["D#7b5", "Eb7b5"], "Dga-C", &["D♯ 7ᵗʰ flat 5ᵗʰ", "E♭ 7ᵗʰ flat 5ᵗʰ"]),
    Chord::new(&["D#+", "Eb+"], "Dgb", &["D♯ augmented", "E♭ augmented"]),
    Chord::new(&["D#7#5", "D#+7", "Eb7#5", "Eb+7"], "Dgb-C", &["D♯ 7ᵗʰ sharp 5ᵗʰ", "D♯ augmented 7ᵗʰ", "E♭ 7ᵗʰ sharp 5ᵗʰ", "E♭ augmented 7ᵗʰ"]),
    Chord::new(&["E"], "eGb", &["E"]),
    Chord::new(&["E5"], "eb", &["E 5ᵗʰ"]),
    Chord::new(&["E7"], "eGb-d", &["E 7ᵗʰ"]),
    Chord::new(&["Emaj7"], "eGb-D", &["E raised 7ᵗʰ"]),
    Chord::new(&["E6"], "eGb-C", &["E 6ᵗʰ"]),
    Chord::new(&["E6/9"], "eGb-CF", &["E 6ᵗʰ added 9ᵗʰ"]),
    Chord::new(&["Eadd2"], "eFGb", &["E added 2ⁿᵈ"]),
    Chord::new(&["Eadd9"], "eGb-F", &["E added 9ᵗʰ"]),
    Chord::new(&["Esus2"], "eFb", &["E suspended 2ⁿᵈ"]),
    Chord::new(&["Esus", "Esus4"], "eab", &["E suspended", "E suspended 4ᵗʰ"]),
    Chord::new(&["E7sus4"], "eab-d", &["E 7ᵗʰ suspended 4ᵗʰ"]),
    Chord::new(&["E9"], "eGb-dF", &["E 9ᵗʰ"]),
    Chord::new(&["Emaj9"], "eGb-DF", &["E raised 9ᵗʰ"]),
    Chord::new(&["E11"], "eGb-dFa", &["E 11ᵗʰ"]),
    Chord::new(&["E13"], "eGb-dFa-C", &["E 13ᵗʰ"]),
    Chord::new(&["Emaj13"], "eGb-DF-C", &["E raised 13ᵗʰ"]),
    Chord::new(&["Em"], "egb", &["E minor"]),
    Chord::new(&["Em6"], "egb-C", &["E minor 6ᵗʰ"]),
    Chord::new(&["Em7"], "egb-d", &["E minor 7ᵗʰ"]),
    Chord::new(&["Emmaj7", "EmM7"], "egb-D", &["E minor raised 7ᵗʰ", "E minor major 7ᵗʰ"]),
    Chord::new(&["Em9"], "egb-dF", &["E minor 9ᵗʰ"]),
    Chord::new(&["Em11"], "egb-dFa", &["E minor 11ᵗʰ"]),
    Chord::new(&["Em7b5"], "egA-d", &["E half-diminished"]),
    Chord::new(&["Edim"], "egA", &["E diminished"]),
    Chord::new(&["Edim7"], "egA-C", &["E diminished 7ᵗʰ"]),
    Chord::new(&["E7b5"], "eGA-d", &["E 7ᵗʰ flat 5ᵗʰ"]),
    Chord::new(&["E+"], "eG-c", &["E augmented"]),
    Chord::new(&["E7#5", "E+7"], "eG-cd", &["E 7ᵗʰ sharp 5ᵗʰ", "E augmented 7ᵗʰ"]),
    Chord::new(&["F"], "fa-c", &["F"]),
    Chord::new(&["F5"], "f-c", &["F 5ᵗʰ"]),
    Chord::new(&["F7"], "fa-cD", &["F 7ᵗʰ"]),
    Chord::new(&["Fmaj7"], "fa-ce", &["F raised 7ᵗʰ"]),
    Chord::new(&["F6"], "fa-cd", &["F 6ᵗʰ"]),
    Chord::new(&["F6/9"], "fa-cdg", &["F 6ᵗʰ added 9ᵗʰ"]),
    Chord::new(&["Fadd2"], "fga-c", &["F added 2ⁿᵈ"]),
    Chord::new(&["Fadd9"], "fa-cg", &["F added 9ᵗʰ"]),
    Chord::new(&["Fsus2"], "fg-c", &["F suspended 2ⁿᵈ"]),
    Chord::new(&["Fsus", "Fsus4"], "fA-c", &["F suspended", "F suspended 4ᵗʰ"]),
    Chord::new(&["F7sus4"], "fA-cD", &["F 7ᵗʰ suspended 4ᵗʰ"]),
    Chord::new(&["F9"], "fa-cDg", &["F 9ᵗʰ"]),
    Chord::new(&["Fmaj9"], "fa-ceg", &["F raised 9ᵗʰ"]),
    Chord::new(&["F11"], "fa-cDgA", &["F 11ᵗʰ"]),
    Chord::new(&["F13"], "fa-cDgA-d", &["F 13ᵗʰ"]),
    Chord::new(&["Fmaj13"], "fa-ceg-d", &["F raised 13ᵗʰ"]),
    Chord::new(&["Fm"], "fG-c", &["F minor"]),
    Chord::new(&["Fm6"], "fG-cd", &["F minor 6ᵗʰ"]),
    Chord::new(&["Fm7"], "fG-cD", &["F minor 7ᵗʰ"]),
    Chord::new(&["Fmmaj7", "FmM7"], "fG-ce", &["F minor raised 7ᵗʰ", "F minor major 7ᵗʰ"]),
    Chord::new(&["Fm9"], "fG-cDg", &["F minor 9ᵗʰ"]),
    Chord::new(&["Fm11"], "fG-cDgA", &["F minor 11ᵗʰ"]),
    Chord::new(&["Fm7b5"], "fGb-D", &["F half-diminished"]),
    Chord::new(&["Fdim"], "fGb", &["F diminished"]),
    Chord::new(&["Fdim7"], "fGb-d", &["F diminished 7ᵗʰ"]),
    Chord::new(&["F7b5"], "fab-D", &["F 7ᵗʰ flat 5ᵗʰ"]),
    Chord::new(&["F+"], "fa-C", &["F augmented"]),
    Chord::new(&["F7#5", "F+7"], "fa-CD", &["F 7ᵗʰ sharp 5ᵗʰ", "F augmented 7ᵗʰ"]),
    Chord::new(&["F#", "Gb"], "FA-C", &["F♯", "G♭"]),
    Chord::new(&["F#5", "Gb5"], "F-C", &["F♯ 5ᵗʰ", "G♭ 5ᵗʰ"]),
    Chord::new(&["F#7", "Gb7"], "FA-Ce", &["F♯ 7ᵗʰ", "G♭ 7ᵗʰ"]),
    Chord::new(&["F#maj7", "Gbmaj7"], "FA-Cf", &["F♯ raised 7ᵗʰ", "G♭ raised 7ᵗʰ"]),
    Chord::new(&["F#6", "Gb6"], "FA-CD", &["F♯ 6ᵗʰ", "G♭ 6ᵗʰ"]),
    Chord::new(&["F#6/9", "Gb6/9"], "FA-CDG", &["F♯ 6ᵗʰ added 9ᵗʰ", "G♭ 6ᵗʰ added 9ᵗʰ"]),
    Chord::new(&["F#add2", "Gbadd2"], "FGA-C", &["F♯ added 2ⁿᵈ", "G♭ added 2ⁿᵈ"]),
    Chord::new(&["F#add9", "Gbadd9"], "FA-CG", &["F♯ added 9ᵗʰ", "G♭ added 9ᵗʰ"]),
    Chord::new(&["F#sus2", "Gbsus2"], "FG-C", &["F♯ suspended 2ⁿᵈ", "G♭ suspended 2ⁿᵈ"]),
    Chord::new(&["F#sus", "F#sus4", "Gbsus", "Gbsus4"], "Fb-C", &["F♯ suspended", "F♯ suspended 4ᵗʰ", "G♭ suspended", "G♭ suspended 4ᵗʰ"]),
    Chord::new(&["F#7sus4", "Gb7sus4"], "Fb-Ce", &["F♯ 7ᵗʰ suspended 4ᵗʰ", "G♭ 7ᵗʰ suspended 4ᵗʰ"]),
    Chord::new(&["F#9", "Gb9"], "FA-CeG", &["F♯ 9ᵗʰ", "G♭ 9ᵗʰ"]),
    Chord::new(&["F#maj9", "Gbmaj9"], "FA-CfG", &["F♯ raised 9ᵗʰ", "G♭ raised 9ᵗʰ"]),
    Chord::new(&["F#11", "Gb11"], "FA-CeGb", &["F♯ 11ᵗʰ", "G♭ 11ᵗʰ"]),
    Chord::new(&["F#13", "Gb13"], "FA-CeGb-D", &["F♯ 13ᵗʰ", "G♭ 13ᵗʰ"]),
    Chord::new(&["F#maj13", "Gbmaj13"], "FA-CfG-D", &["F♯ raised 13ᵗʰ", "G♭ raised 13ᵗʰ"]),
    Chord::new(&["F#m", "Gbm"], "Fa-C", &["F♯ minor", "G♭ minor"]),
    Chord::new(&["F#m6", "Gbm6"], "Fa-CD", &["F♯ minor 6ᵗʰ", "G♭ minor 6ᵗʰ"]),
    Chord::new(&["F#m7", "Gbm7"], "Fa-Ce", &["F♯ minor 7ᵗʰ", "G♭ minor 7ᵗʰ"]),
    Chord::new(&["F#mmaj7", "F#mM7", "Gbmmaj7", "GbmM7"], "Fa-Cf", &["F♯ minor raised 7ᵗʰ", "F♯ minor major 7ᵗʰ", "G♭ minor raised 7ᵗʰ", "G♭ minor major 7ᵗʰ"]),
    Chord::new(&["F#m9", "Gbm9"], "Fa-CeG", &["F♯ minor 9ᵗʰ", "G♭ minor 9ᵗʰ"]),
    Chord::new(&["F#m11", "Gbm11"], "Fa-CeGb", &["F♯ minor 11ᵗʰ", "G♭ minor 11ᵗʰ"]),
    Chord::new(&["F#m7b5", "Gbm7b5"], "Fa-ce", &["F♯ half-diminished", "G♭ half-diminished"]),
    Chord::new(&["F#dim", "Gbdim"], "Fa-c", &["F♯ diminished", "G♭ diminished"]),
    Chord::new(&["F#dim7", "Gbdim7"], "Fa-cD", &["F♯ diminished 7ᵗʰ", "G♭ diminished 7ᵗʰ"]),
    Chord::new(&["F#7b5", "Gb7b5"], "FA-ce", &["F♯ 7ᵗʰ flat 5ᵗʰ", "G♭ 7ᵗʰ flat 5ᵗʰ"]),
    Chord::new(&["F#+", "Gb+"], "FA-d", &["F♯ augmented", "G♭ augmented"]),
    Chord::new(&["F#7#5", "F#+7", "Gb7#5", "Gb+7"], "FA-de", &["F♯ 7ᵗʰ sharp 5ᵗʰ", "F♯ augmented 7ᵗʰ", "G♭ 7ᵗʰ sharp 5ᵗʰ", "G♭ augmented 7ᵗʰ"]),
    Chord::new(&["G"], "gb-d", &["G"]),
    Chord::new(&["G5"], "g-d", &["G 5ᵗʰ"]),
    Chord::new(&["G7"], "gb-df", &["G 7ᵗʰ"]),
    Chord::new(&["Gmaj7"], "gb-dF", &["G raised 7ᵗʰ"]),
    Chord::new(&["G6"], "gb-de", &["G 6ᵗʰ"]),
    Chord::new(&["G6/9"], "gb-dea", &["G 6ᵗʰ added 9ᵗʰ"]),
    Chord::new(&["Gadd2"], "gab-d", &["G added 2ⁿᵈ"]),
    Chord::new(&["Gadd9"], "gb-da", &["G added 9ᵗʰ"]),
    Chord::new(&["Gsus2"], "ga-d", &["G suspended 2ⁿᵈ"]),
    Chord::new(&["Gsus", "Gsus4"], "g-cd", &["G suspended", "G suspended 4ᵗʰ"]),
    Chord::new(&["G7sus4"], "g-cdf", &["G 7ᵗʰ suspended 4ᵗʰ"]),
    Chord::new(&["G9"], "gb-dfa", &["G 9ᵗʰ"]),
    Chord::new(&["Gmaj9"], "gb-dFa", &["G raised 9ᵗʰ"]),
    Chord::new(&["G11"], "gb-dfa-c", &["G 11ᵗʰ"]),
    Chord::new(&["G13"], "gb-dfa-ce", &["G 13ᵗʰ"]),
    Chord::new(&["Gmaj13"], "gb-dFa-e", &["G raised 13ᵗʰ"]),
    Chord::new(&["Gm"], "gA-d", &["G minor"]),
    Chord::new(&["Gm6"], "gA-de", &["G minor 6ᵗʰ"]),
    Chord::new(&["Gm7"], "gA-df", &["G minor 7ᵗʰ"]),
    Chord::new(&["Gmmaj7", "GmM7"], "gA-dF", &["G minor raised 7ᵗʰ", "G minor major 7ᵗʰ"]),
    Chord::new(&["Gm9"], "gA-dfa", &["G minor 9ᵗʰ"]),
    Chord::new(&["Gm11"], "gA-dfa-c", &["G minor 11ᵗʰ"]),
    Chord::new(&["Gm7b5"], "gA-Cf", &["G half-diminished"]),
    Chord::new(&["Gdim"], "gA-C", &["G diminished"]),
    Chord::new(&["Gdim7"], "gA-Ce", &["G diminished 7ᵗʰ"]),
    Chord::new(&["G7b5"], "gb-Cf", &["G 7ᵗʰ flat 5ᵗʰ"]),
    Chord::new(&["G+"], "gb-D", &["G augmented"]),
    Chord::new(&["G7#5", "G+7"], "gb-Df", &["G 7ᵗʰ sharp 5ᵗʰ", "G augmented 7ᵗʰ"]),
    Chord::new(&["G#", "Ab"], "G-cD", &["G♯", "A♭"]),
    Chord::new(&["G#5", "Ab5"], "G-D", &["G♯ 5ᵗʰ", "A♭ 5ᵗʰ"]),
    Chord::new(&["G#7", "Ab7"], "G-cDF", &["G♯ 7ᵗʰ", "A♭ 7ᵗʰ"]),
    Chord::new(&["G#maj7", "Abmaj7"], "G-cDg", &["G♯ raised 7ᵗʰ", "A♭ raised 7ᵗʰ"]),
    Chord::new(&["G#6", "Ab6"], "G-cDf", &["G♯ 6ᵗʰ", "A♭ 6ᵗʰ"]),
    Chord::new(&["G#6/9", "Ab6/9"], "G-cDfA", &["G♯ 6ᵗʰ added 9ᵗʰ", "A♭ 6ᵗʰ added 9ᵗʰ"]),
    Chord::new(&["G#add2", "Abadd2"], "GA-cD", &["G♯ added 2ⁿᵈ", "A♭ added 2ⁿᵈ"]),
    Chord::new(&["G#add9", "Abadd9"], "G-cDA", &["G♯ added 9ᵗʰ", "A♭ added 9ᵗʰ"]),
    Chord::new(&["G#sus2", "Absus2"], "GA-D", &["G♯ suspended 2ⁿᵈ", "A♭ suspended 2ⁿᵈ"]),
    Chord::new(&["G#sus", "G#sus4", "Absus", "Absus4"], "G-CD", &["G♯ suspended", "G♯ suspended 4ᵗʰ", "A♭ suspended", "A♭ suspended 4ᵗʰ"]),
    Chord::new(&["G#7sus4", "Ab7sus4"], "G-CDF", &["G♯ 7ᵗʰ suspended 4ᵗʰ", "A♭ 7ᵗʰ suspended 4ᵗʰ"]),
    Chord::new(&["G#9", "Ab9"], "G-cDFA", &["G♯ 9ᵗʰ", "A♭ 9ᵗʰ"]),
    Chord::new(&["G#maj9", "Abmaj9"], "G-cDgA", &["G♯ raised 9ᵗʰ", "A♭ raised 9ᵗʰ"]),
    Chord::new(&["G#11", "Ab11"], "G-cDFA-C", &["G♯ 11ᵗʰ", "A♭ 11ᵗʰ"]),
    Chord::new(&["G#13", "Ab13"], "G-cDFA-Cf", &["G♯ 13ᵗʰ", "A♭ 13ᵗʰ"]),
    Chord::new(&["G#maj13", "Abmaj13"], "G-cDgA-f", &["G♯ raised 13ᵗʰ", "A♭ raised 13ᵗʰ"]),
    Chord::new(&["G#m", "Abm"], "Gb-D", &["G♯ minor", "A♭ minor"]),
    Chord::new(&["G#m6", "Abm6"], "Gb-Df", &["G♯ minor 6ᵗʰ", "A♭ minor 6ᵗʰ"]),
    Chord::new(&["G#m7", "Abm7"], "Gb-DF", &["G♯ minor 7ᵗʰ", "A♭ minor 7ᵗʰ"]),
    Chord::new(&["G#mmaj7", "G#mM7", "Abmmaj7", "AbmM7"], "Gb-Dg", &["G♯ minor raised 7ᵗʰ", "G♯ minor major 7ᵗʰ", "A♭ minor raised 7ᵗʰ", "A♭ minor major 7ᵗʰ"]),
    Chord::new(&["G#m9", "Abm9"], "Gb-DFA", &["G♯ minor 9ᵗʰ", "A♭ minor 9ᵗʰ"]),
    Chord::new(&["G#m11", "Abm11"], "Gb-DFA-C", &["G♯ minor 11ᵗʰ", "A♭ minor 11ᵗʰ"]),
    Chord::new(&["G#m7b5", "Abm7b5"], "Gb-dF", &["G♯ half-diminished", "A♭ half-diminished"]),
    Chord::new(&["G#dim", "Abdim"], "Gb-d", &["G♯ diminished", "A♭ diminished"]),
    Chord::new(&["G#dim7", "Abdim7"], "Gb-df", &["G♯ diminished 7ᵗʰ", "A♭ diminished 7ᵗʰ"]),
    Chord::new(&["G#7b5", "Ab7b5"], "G-cdF", &["G♯ 7ᵗʰ flat 5ᵗʰ", "A♭ 7ᵗʰ flat 5ᵗʰ"]),
    Chord::new(&["G#+", "Ab+"], "G-ce", &["G♯ augmented", "A♭ augmented"]),
    Chord::new(&["G#7#5", "G#+7", "Ab7#5", "Ab+7"], "G-ceF", &["G♯ 7ᵗʰ sharp 5ᵗʰ", "G♯ augmented 7ᵗʰ", "A♭ 7ᵗʰ sharp 5ᵗʰ", "A♭ augmented 7ᵗʰ"]),
    Chord::new(&["A"], "a-Ce", &["A"]),
    Chord::new(&["A5"], "a-e", &["A 5ᵗʰ"]),
    Chord::new(&["A7"], "a-Ceg", &["A 7ᵗʰ"]),
    Chord::new(&["Amaj7"], "a-CeG", &["A raised 7ᵗʰ"]),
    Chord::new(&["A6"], "a-CeF", &["A 6ᵗʰ"]),
    Chord::new(&["A6/9"], "a-CeFb", &["A 6ᵗʰ added 9ᵗʰ"]),
    Chord::new(&["Aadd2"], "ab-Ce", &["A added 2ⁿᵈ"]),
    Chord::new(&["Aadd9"], "a-Ceb", &["A added 9ᵗʰ"]),
    Chord::new(&["Asus2"], "ab-e", &["A suspended 2ⁿᵈ"]),
    Chord::new(&["Asus", "Asus4"], "a-de", &["A suspended", "A suspended 4ᵗʰ"]),
    Chord::new(&["A7sus4"], "a-deg", &["A 7ᵗʰ suspended 4ᵗʰ"]),
    Chord::new(&["A9"], "a-Cegb", &["A 9ᵗʰ"]),
    Chord::new(&["Amaj9"], "a-CeGb", &["A raised 9ᵗʰ"]),
    Chord::new(&["A11"], "a-Cegb-d", &["A 11ᵗʰ"]),
    Chord::new(&["A13"], "a-Cegb-dF", &["A 13ᵗʰ"]),
    Chord::new(&["Amaj13"], "a-CeGb-F", &["A raised 13ᵗʰ"]),
    Chord::new(&["Am"], "a-ce", &["A minor"]),
    Chord::new(&["Am6"], "a-ceF", &["A minor 6ᵗʰ"]),
    Chord::new(&["Am7"], "a-ceg", &["A minor 7ᵗʰ"]),
    Chord::new(&["Ammaj7", "AmM7"], "a-ceG", &["A minor raised 7ᵗʰ", "A minor major 7ᵗʰ"]),
    Chord::new(&["Am9"], "a-cegb", &["A minor 9ᵗʰ"]),
    Chord::new(&["Am11"], "a-cegb-d", &["A minor 11ᵗʰ"]),
    Chord::new(&["Am7b5"], "a-cDg", &["A half-diminished"]),
    Chord::new(&["Adim"], "a-cD", &["A diminished"]),
    Chord::new(&["Adim7"], "a-cDF", &["A diminished 7ᵗʰ"]),
    Chord::new(&["A7b5"], "a-CDg", &["A 7ᵗʰ flat 5ᵗʰ"]),
    Chord::new(&["A+"], "a-Cf", &["A augmented"]),
    Chord::new(&["A7#5", "A+7"], "a-Cfg", &["A 7ᵗʰ sharp 5ᵗʰ", "A augmented 7ᵗʰ"]),
    Chord::new(&["A#", "Bb"], "A-df", &["A♯", "B♭"]),
    Chord::new(&["A#5", "Bb5"], "A-f", &["A♯ 5ᵗʰ", "B♭ 5ᵗʰ"]),
    Chord::new(&["A#7", "Bb7"], "A-dfG", &["A♯ 7ᵗʰ", "B♭ 7ᵗʰ"]),
    Chord::new(&["A#maj7", "Bbmaj7"], "A-dfa", &["A♯ raised 7ᵗʰ", "B♭ raised 7ᵗʰ"]),
    Chord::new(&["A#6", "Bb6"], "A-dfg", &["A♯ 6ᵗʰ", "B♭ 6ᵗʰ"]),
    Chord::new(&["A#6/9", "Bb6/9"], "A-dfg-c", &["A♯ 6ᵗʰ added 9ᵗʰ", "B♭ 6ᵗʰ added 9ᵗʰ"]),
    Chord::new(&["A#add2", "Bbadd2"], "A-cdf", &["A♯ added 2ⁿᵈ", "B♭ added 2ⁿᵈ"]),
    Chord::new(&["A#add9", "Bbadd9"], "A-df-c", &["A♯ added 9ᵗʰ", "B♭ added 9ᵗʰ"]),
    Chord::new(&["A#sus2", "Bbsus2"], "A-cf", &["A♯ suspended 2ⁿᵈ", "B♭ suspended 2ⁿᵈ"]),
    Chord::new(&["A#sus", "A#sus4", "Bbsus", "Bbsus4"], "A-Df", &["A♯ suspended", "A♯ suspended 4ᵗʰ", "B♭ suspended", "B♭ suspended 4ᵗʰ"]),
    Chord::new(&["A#7sus4", "Bb7sus4"], "A-DfG", &["A♯ 7ᵗʰ suspended 4ᵗʰ", "B♭ 7ᵗʰ suspended 4ᵗʰ"]),
    Chord::new(&["A#9", "Bb9"], "A-dfG-c", &["A♯ 9ᵗʰ", "B♭ 9ᵗʰ"]),
    Chord::new(&["A#maj9", "Bbmaj9"], "A-dfa-c", &["A♯ raised 9ᵗʰ", "B♭ raised 9ᵗʰ"]),
    Chord::new(&["A#11", "Bb11"], "A-dfG-cD", &["A♯ 11ᵗʰ", "B♭ 11ᵗʰ"]),
    Chord::new(&["A#13", "Bb13"], "A-dfG-cDg", &["A♯ 13ᵗʰ", "B♭ 13ᵗʰ"]),
    Chord::new(&["A#maj13", "Bbmaj13"], "A-dfa-cg", &["A♯ raised 13ᵗʰ", "B♭ raised 13ᵗʰ"]),
    Chord::new(&["A#m", "Bbm"], "A-Cf", &["A♯ minor", "B♭ minor"]),
    Chord::new(&["A#m6", "Bbm6"], "A-Cfg", &["A♯ minor 6ᵗʰ", "B♭ minor 6ᵗʰ"]),
    Chord::new(&["A#m7", "Bbm7"], "A-CfG", &["A♯ minor 7ᵗʰ", "B♭ minor 7ᵗʰ"]),
    Chord::new(&["A#mmaj7", "A#mM7", "Bbmmaj7", "BbmM7"], "A-Cfa", &["A♯ minor raised 7ᵗʰ", "A♯ minor major 7ᵗʰ", "B♭ minor raised 7ᵗʰ", "B♭ minor major 7ᵗʰ"]),
    Chord::new(&["A#m9", "Bbm9"], "A-CfG-c", &["A♯ minor 9ᵗʰ", "B♭ minor 9ᵗʰ"]),
    Chord::new(&["A#m11", "Bbm11"], "A-CfG-cD", &["A♯ minor 11ᵗʰ", "B♭ minor 11ᵗʰ"]),
    Chord::new(&["A#m7b5", "Bbm7b5"], "A-CeG", &["A♯ half-diminished", "B♭ half-diminished"]),
    Chord::new(&["A#dim", "Bbdim"], "A-Ce", &["A♯ diminished", "B♭ diminished"]),
    Chord::new(&["A#dim7", "Bbdim7"], "A-Ceg", &["A♯ diminished 7ᵗʰ", "B♭ diminished 7ᵗʰ"]),
    Chord::new(&["A#7b5", "Bb7b5"], "A-deG", &["A♯ 7ᵗʰ flat 5ᵗʰ", "B♭ 7ᵗʰ flat 5ᵗʰ"]),
    Chord::new(&["A#+", "Bb+"], "A-dF", &["A♯ augmented", "B♭ augmented"]),
    Chord::new(&["A#7#5", "A#+7", "Bb7#5", "Bb+7"], "A-dFG", &["A♯ 7ᵗʰ sharp 5ᵗʰ", "A♯ augmented 7ᵗʰ", "B♭ 7ᵗʰ sharp 5ᵗʰ", "B♭ augmented 7ᵗʰ"]),
    Chord::new(&["B"], "b-DF", &["B"]),
    Chord::new(&["B5"], "b-F", &["B 5ᵗʰ"]),
    Chord::new(&["B7"], "b-DFa", &["B 7ᵗʰ"]),
    Chord::new(&["Bmaj7"], "b-DFA", &["B raised 7ᵗʰ"]),
    Chord::new(&["B6"], "b-DFG", &["B 6ᵗʰ"]),
    Chord::new(&["B6/9"], "b-DFG-C", &["B 6ᵗʰ added 9ᵗʰ"]),
    Chord::new(&["Badd2"], "b-CDF", &["B added 2ⁿᵈ"]),
    Chord::new(&["Badd9"], "b-DF-C", &["B added 9ᵗʰ"]),
    Chord::new(&["Bsus2"], "b-CF", &["B suspended 2ⁿᵈ"]),
    Chord::new(&["Bsus", "Bsus4"], "b-eF", &["B suspended", "B suspended 4ᵗʰ"]),
    Chord::new(&["B7sus4"], "b-eFa", &["B 7ᵗʰ suspended 4ᵗʰ"]),
    Chord::new(&["B9"], "b-DFa-C", &["B 9ᵗʰ"]),
    Chord::new(&["Bmaj9"], "b-DFA-C", &["B raised 9ᵗʰ"]),
    Chord::new(&["B11"], "b-DFa-Ce", &["B 11ᵗʰ"]),
    Chord::new(&["B13"], "b-DFa-CeG", &["B 13ᵗʰ"]),
    Chord::new(&["Bmaj13"], "b-DFA-CG", &["B raised 13ᵗʰ"]),
    Chord::new(&["Bm"], "b-dF", &["B minor"]),
    Chord::new(&["Bm6"], "b-dFG", &["B minor 6ᵗʰ"]),
    Chord::new(&["Bm7"], "b-dFa", &["B minor 7ᵗʰ"]),
    Chord::new(&["Bmmaj7", "BmM7"], "b-dFA", &["B minor raised 7ᵗʰ", "B minor major 7ᵗʰ"]),
    Chord::new(&["Bm9"], "b-dFa-C", &["B minor 9ᵗʰ"]),
    Chord::new(&["Bm11"], "b-dFa-Ce", &["B minor 11ᵗʰ"]),
    Chord::new(&["Bm7b5"], "b-dfa", &["B half-diminished"]),
    Chord::new(&["Bdim"], "b-df", &["B diminished"]),
    Chord::new(&["Bdim7"], "b-dfG", &["B diminished 7ᵗʰ"]),
    Chord::new(&["B7b5"], "b-Dfa", &["B 7ᵗʰ flat 5ᵗʰ"]),
    Chord::new(&["B+"], "b-Dg", &["B augmented"]),
    Chord::new(&["B7#5", "B+7"], "b-Dga", &["B 7ᵗʰ sharp 5ᵗʰ", "B augmented 7ᵗʰ"]),
    // slash / inversion chords, e.g.
    // A/C♯ is an A major chord with C♯ as the bass note or
    // A/E is an A major chord with E as the bass note
    // pianochord.org/a-major.html#hide1
    Chord::new(&["C/E"], "eg-c", &["C over E"]),
    Chord::new(&["C/G"], "g-ce", &["C over G"]),
    Chord::new(&["Cm/D#", "Cm/Eb"], "Dg-c", &["C minor over D♯", "C minor over E♭"]),
    Chord::new(&["Cm/G"], "g-cD", &["C minor over G"]),
    Chord::new(&["C#/F", "Db/F"], "fG-C", &["C♯ over F", "D♭ over F"]),
    Chord::new(&["C#/G#", "Db/Ab"], "G-Cf", &["C♯ over G♯", "D♭ over A♭"]),
    Chord::new(&["C#m/E", "Dbm/E"], "eG-C", &["C♯ minor over E", "D♭ minor over E"]),
    Chord::new(&["C#m/G#", "Dbm/Ab"], "G-Ce", &["C♯ minor over G♯", "D♭ minor over A♭"]),
    Chord::new(&["D/F#", "D/Gb"], "Fa-d", &["D over F♯", "D over G♭"]),
    Chord::new(&["D/A"], "a-dF", &["D over A"]),
    Chord::new(&["Dm/F"], "fa-d", &["D minor over F"]),
    Chord::new(&["Dm/A"], "a-df", &["D minor over A"]),
    Chord::new(&["D#/G", "Eb/G"], "gA-D", &["D♯ over G", "E♭ over G"]),
    Chord::new(&["D#/A#", "Eb/Bb"], "A-Dg", &["D♯ over A♯", "E♭ over B♭"]),
    Chord::new(&["D#m/F#", "Ebm/Gb"], "FA-D", &["D♯ minor over F♯", "E♭ minor over G♭"]),
    Chord::new(&["D#m/A#", "Ebm/Bb"], "A-DF", &["D♯ minor over A♯", "E♭ minor over B♭"]),
    Chord::new(&["E/G#", "E/Ab"], "Gb-e", &["E over G♯", "E over A♭"]),
    Chord::new(&["E/B"], "b-eG", &["E over B"]),
    Chord::new(&["Em/G"], "gb-e", &["E minor over G"]),
    Chord::new(&["Em/B"], "b-eg", &["E minor over B"]),
    Chord::new(&["F/A"], "a-cf", &["F over A"]),
    Chord::new(&["F/C"], "cfa", &["F over C"]),
    Chord::new(&["Fm/G#", "Fm/Ab"], "G-cf", &["F minor over G♯", "F minor over A♭"]),
    Chord::new(&["Fm/C"], "cfG", &["F minor over C"]),
    Chord::new(&["F#/A#", "Gb/Bb"], "A-CF", &["F♯ over A♯", "G♭ over B♭"]),
    Chord::new(&["F#/C#", "Gb/Db"], "CFA", &["F♯ over C♯", "G♭ over D♭"]),
    Chord::new(&["F#m/A", "Gbm/A"], "a-CF", &["F♯ minor over A", "G♭ minor over A"]),
    Chord::new(&["F#m/C#", "Gbm/Db"], "CFa", &["F♯ minor over C♯", "G♭ minor over D♭"]),
    Chord::new(&["G/B"], "b-dg", &["G over B"]),
    Chord::new(&["G/D"], "dgb", &["G over D"]),
    Chord::new(&["Gm/A#", "Gm/Bb"], "A-dg", &["G minor over A♯", "G minor over B♭"]),
    Chord::new(&["Gm/D"], "dgA", &["G minor over D"]),
    Chord::new(&["G#/C", "Ab/C"], "cDG", &["G♯ over C", "A♭ over C"]),
    Chord::new(&["G#/D#", "Ab/Eb"], "DG-c", &["G♯ over D♯", "A♭ over E♭"]),
    Chord::new(&["G#m/B", "Abm/B"], "b-DG", &["G♯ minor over B", "A♭ minor over B"]),
    Chord::new(&["G#m/D#", "Abm/Eb"], "DGb", &["G♯ minor over D♯", "A♭ minor over E♭"]),
    Chord::new(&["A/C#", "A/Db"], "Cea", &["A over C♯", "A over D♭"]),
    Chord::new(&["A/E"], "ea-C", &["A over E"]),
    Chord::new(&["Am/C"], "cea", &["A minor over C"]),
    Chord::new(&["Am/E"], "ea-c", &["A minor over E"]),
    Chord::new(&["A#/D", "Bb/D"], "dfA", &["A♯ over D", "B♭ over D"]),
    Chord::new(&["A#/F", "Bb/F"], "fA-d", &["A♯ over F", "B♭ over F"]),
    Chord::new(&["A#m/C#", "Bbm/Db"], "CfA", &["A♯ minor over C♯", "B♭ minor over D♭"]),
    Chord::new(&["A#m/F", "Bbm/F"], "fA-C", &["A♯ minor over F", "B♭ minor over F"]),
    Chord::new(&["B/D#", "B/Eb"], "DFb", &["B over D♯", "B over E♭"]),
    Chord::new(&["B/F#", "B/Gb"], "Fb-D", &["B over F♯", "B over G♭"]),
    Chord::new(&["Bm/D"], "dFb", &["B minor over D"]),
    Chord::new(&["Bm/F#", "Bm/Gb"], "Fb-d", &["B minor over F♯", "B minor over G♭"]),
    // sources
    // pianochord.org (chord types, formulas and inversions)
    // pianowithjonny.com/piano-lessons/major-7th-chords-for-piano-a-complete-guide
    // pianowithjonny.com/piano-lessons/7th-chords-for-piano-the-complete-guide*
    // slash chords / inversions : piano-lessons-info.com/fmajorchord.html
];

pub static ALL_CHORDS_BY_SHORT_NAMES: Lazy<HashMap<String, Vec<&'static Chord<'static>>>> =
    Lazy::new(|| {
        let mut map = HashMap::<_, Vec<_>>::new();

        for chord in ALL_CHORDS {
            for sn in chord.short_names {
                map.entry(sn.to_ascii_lowercase()).or_default().push(chord);
            }
        }
        map
    });

#[cfg(test)]
mod tests {
    // NOTE: useful idiom - importing names from outer (for mod tests) scope.
    use super::*;

    #[test]
    fn test_valid_chars() {
        for chord in ALL_CHORDS {
            for chr in chord.pattern.chars() {
                assert!(
                    "abcdefgACDFG-".contains(chr),
                    "chr={:?} pattern={:?}",
                    chr,
                    chord.pattern
                );
            }
        }
    }

    #[test]
    fn test_aliases() {
        for chord in ALL_CHORDS {
            assert_eq!(
                chord.short_names.len(),
                chord.names.len(),
                "Alias issue short_names={:?} names={:?}",
                chord.short_names,
                chord.names
            )
        }
    }

    #[test]
    fn test_unique_short_names() {
        // lookups are case insensitive, see `ALL_CHORDS_BY_SHORT_NAMES`
        let mut seen = HashMap::<String, &str>::new();
        for chord in ALL_CHORDS {
            for sn in chord.short_names {
                if let Some(prev) = seen.insert(sn.to_ascii_lowercase(), sn) {
                    panic!("Duplicated short name {:?} (also {:?})", sn, prev)
                }
            }
        }
    }

    #[test]
    fn test_ascending_patterns() {
        for chord in ALL_CHORDS {
            let (mut octave, mut prev) = (0i32, -1i32);
            for chr in chord.pattern.chars() {
                if chr == '-' {
                    octave += 12;
                    continue;
                }
                let semitone = octave
                    + match chr {
                        'c' => 0,
                        'C' => 1,
                        'd' => 2,
                        'D' => 3,
                        'e' => 4,
                        'f' => 5,
                        'F' => 6,
                        'g' => 7,
                        'G' => 8,
                        'a' => 9,
                        'A' => 10,
                        'b' => 11,
                        _ => panic!("Unrecognized character ch={:?}", chr),
                    };
                assert!(
                    semitone > prev,
                    "Not ascending chr={:?} pattern={:?}",
                    chr,
                    chord.pattern
                );
                prev = semitone;
            }
        }
    }
}
