name: ci

on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly

    steps:
    - uses: actions/checkout@v7
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - run: cargo fmt --check
    - run: RUSTFLAGS='-D warnings' cargo check
    - run: cargo build --verbose
    - run: cargo test --verbose
